import Link from "next/link";
import SiteHeader from "@/components/SiteHeader";
import SiteFooter from "@/components/SiteFooter";

export default function HomePage() {
  return (
    <>
      <SiteHeader variant="public" />

      <section className="hero">
        <div className="container">
          <div className="hero-carousel">
            <div className="carousel-art" />
            <p>AI-generated timetable adapts daily to your exam date, weak topics &amp; available hours</p>
            <div className="carousel-dots">
              <span className="active" />
              <span />
              <span />
              <span />
            </div>
          </div>
          <div className="hero-copy">
            <div className="eyebrow">Smart Learning Platform</div>
            <h1>
              From Classroom
              <br />
              to Career.
            </h1>
            <p>
              Prepare smarter. Personalized exam plans, AI career guidance, and adaptive MCQ tests — built for
              Pakistani students at every level.
            </p>
            <Link href="/register" className="btn btn-primary">
              Register on Portal ↗
            </Link>
            <p className="login-hint">
              Already have an account? <Link href="/login">Login here</Link>
            </p>
          </div>
        </div>
      </section>

      <section className="section">
        <div className="container">
          <div className="section-heading">What Mentora Offers</div>
          <div className="card-grid-4">
            <div className="info-card">
              <div className="icon-swatch swatch-mint" />
              <h3>Smart Exam Prep</h3>
              <p>AI timetable &amp; adaptive MCQs personalized to your weak topics and exam date</p>
            </div>
            <div className="info-card">
              <div className="icon-swatch swatch-sage" />
              <h3>Career Counseling</h3>
              <p>Gap analysis, 50+ career-fit rankings &amp; 6-month roadmaps generated from your CV</p>
            </div>
            <div className="info-card">
              <div className="icon-swatch swatch-peach" />
              <h3>Video Playlists</h3>
              <p>Auto-curated YouTube videos per topic, added to your personal learning portal</p>
            </div>
            <div className="info-card">
              <div className="icon-swatch swatch-sky" />
              <h3>MCQ Assignments</h3>
              <p>Topic-based tests generated by AI that flag knowledge gaps instantly after each session</p>
            </div>
          </div>
        </div>
      </section>

      <section className="section section-tint">
        <div className="container">
          <div className="section-heading">How It Works</div>
          <div className="steps-row">
            <div className="step is-current">
              <div className="step-circle">1</div>
              <p>Register &amp; create profile</p>
            </div>
            <div className="step-line" />
            <div className="step">
              <div className="step-circle">2</div>
              <p>Choose exam or career goal</p>
            </div>
            <div className="step-line" />
            <div className="step">
              <div className="step-circle">3</div>
              <p>Get AI timetable</p>
            </div>
            <div className="step-line" />
            <div className="step">
              <div className="step-circle">4</div>
              <p>Study, practice &amp; take MCQs</p>
            </div>
            <div className="step-line" />
            <div className="step">
              <div className="step-circle">5</div>
              <p>Get career fit report</p>
            </div>
          </div>
        </div>
      </section>

      <section className="section">
        <div className="container">
          <div className="section-heading" style={{ textAlign: "left" }}>
            Announcements &amp; Updates
          </div>
          <div className="announcement-list">
            <div className="announcement new">
              <span className="tag-pill">New Feature</span>
              <div className="headline">
                📺 YouTube playlist auto-added after each study session — no manual searching
              </div>
              <div className="date">Released June 2025</div>
            </div>
            <div className="announcement content">
              <span className="tag-pill">Content</span>
              <div className="headline">📗 MDCAT Biology Full Syllabus 2025 — now available in Learning Portal</div>
              <div className="date">May 2025</div>
            </div>
            <div className="announcement module">
              <span className="tag-pill">New Module</span>
              <div className="headline">
                🎖️ ISSB, Army, Navy &amp; PAF test prep content added to Exam Prep module
              </div>
              <div className="date">April 2025</div>
            </div>
          </div>
          <div className="ad-banner">Sponsored — [ Advertisement Banner ] · Contextual ads area</div>
        </div>
      </section>

      <SiteFooter />
    </>
  );
}
